language: r
cache: packages
sudo: false

r_packages:
  - roxygen2
  - devtools
  - XML
  - yaml

script:
  - Rscript -e 'library(devtools); checkOutput <- data.frame(test()); if (sum(checkOutput["failed"]) > 0){q(status = 1, save = "no")}'
